# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PAUgyu4Ti2vn2nGmt-Z0SxT7d8Rw0BfX

# Autonomous Content Specialist Crew

This notebook orchestrates an autonomous editorial team that runs entirely within the free tier of Google Gemini, transforming raw developer expertise into high-impact industry content.

1. **The Profile Analyst** extracts your core technical strengths, unique engineering perspectives, and authoritative voice.
2. **The Market Researcher** analyzes target topics to uncover current industry trends, audience pain points, and content gaps.
3. **The Editorial Strategist** cross-references your expertise against market demand, scoring and selecting the highest-impact article angle.
4. **The Specialist Copywriter** drafts a polished, highly engaging, and authoritative long-form article or LinkedIn post based on the winning strategy.
"""

# Install dependencies
!pip install -q crewai crewai-tools
print('✅ Done')

"""
### Instructions to Input API Key:
To run this notebook securely without editing a single line of code, add your Gemini API key to your Colab Secrets:
1. Click the **Key icon (Secrets)** 🔑 on the left sidebar of Google Colab.
2. Add a new secret named exactly `GEMINI_API_KEY`.
3. Paste your free API key from Google AI Studio(https://aistudio.google.com/api-keys) into the Value field.
4. Toggle the **"Notebook access"** switch to **ON**.

*The script below will automatically pull this secret out of your vault, keeping your keys 100% invisible inside the code cells.*
"""

# Load API key (add GEMINI_API_KEY in Colab secrets)
from google.colab import userdata
import os

# Retrieve the API key from Colab's secrets manager
GEMINI_API_KEY = userdata.get('GEMINI_API_KEY') # Add '#' at beginning if not using this method

# Retrieve the API key from user directly
#os.environ["GEMINI_API_KEY"] = "****Paste YOUR_GEMINI_KEY here******"
# Remove '#' in the line above to execute externally without Google Colab

print('API Key successfully retrieved')

# Imports
from crewai import Agent, Task, Crew, Process, LLM

gemini_llm = LLM(
    model="gemini/gemini-2.5-flash",
    api_key=GEMINI_API_KEY,
    temperature=0.3,
)
print('Imported the required libraries and llm was defined successfully')

"""# Your Inputs
Insert your inputs below

"""

#Change everything in the quotations ("") to your desired preferences to help the AI understand the background

MY_EXPERTISE = """
I am a computer science student with basic knowledge of Python, HTML, CSS,
and programming fundamentals. I am exploring artificial intelligence and
want to understand how modern AI systems are built.
"""

TARGET_TOPICS = [
    "Introduction to large language models",
    "Building AI applications as a beginner"
]

"""# The Agents"""

expertise_analyst = Agent(
    role="Expertise & Profile Analyst",
    goal="Analyze the author's background and extract their core strengths, unique perspectives, and authoritative voice.",
    backstory="You are an expert personal branding coach. You read an author's background and figure out exactly what they are qualified to talk about so they sound like an industry veteran.",
    llm=gemini_llm,
    verbose=True
)

topic_researcher = Agent(
    role="Market Topic Researcher",
    goal="Analyze the target topics using your deep internal knowledge of the referred industry to identify current trends, pain points, and what audiences want to read.",
    backstory="You are a brilliant industry analyst. Instead of searching the web, you draw upon your vast knowledge of the topic, current trends, and enterprise business needs to predict exactly what content is highly sought after right now.",
    llm=gemini_llm,
    verbose=True
)

content_fit_scorer = Agent(
    role="Content-Fit Scorer & Strategist",
    goal="Compare the author's expertise against the market research to find the absolute best, highest-scoring angle for an article.",
    backstory="You are a strict Managing Editor. You match what the author knows (Expertise) with what the market wants (Research) and score the overlapping angles out of 100 to find the winning idea.",
    llm=gemini_llm,
    verbose=True
)

content_writer = Agent(
    role="Specialist Content Writer",
    goal="Draft a highly engaging, authoritative article or LinkedIn post based on the winning angle.",
    backstory="You are a world-class copywriter and ghostwriter. You take strategic angles and turn them into compelling, easy-to-read content that drives engagement.",
    llm=gemini_llm,
    verbose=True
)

print('Agents defined successfully')

"""System Guardrail (DO NOT CHANGE)"""

def get_system_guardrail(topics):
    return f'''
    CRITICAL SYSTEM OVERRIDE & COMPLIANCE RULES:
    1. You are strictly forbidden from writing about or researching ANY topic outside of: {topics}.
    2. Do not invent tutorials, do not pivot to local Python tools, and do not hallucinate unrelated concepts.
    3. If your output does not directly address the target topics, you have failed your core directive.
    '''

"""# Assigning Tasks to the Agents"""

task_expertise = Task(
    description=f"Analyze this background: {MY_EXPERTISE}. Extract the top 3 unique selling points and areas of authority.",
    expected_output="A bulleted list of the author's core strengths.",
    agent=expertise_analyst
)

task_research = Task(
    description=f"Analyze these target topics: {TARGET_TOPICS}. Identify the biggest trends and what audiences want to read about them right now." + get_system_guardrail(TARGET_TOPICS),
    expected_output="A market research report detailing current trends.",
    agent=topic_researcher
)

task_score = Task(
    description="Compare the author's strengths against the market research. Generate 3 article angles. Score them out of 100 based on fit, and pick the ultimate winner." + get_system_guardrail(TARGET_TOPICS),
    expected_output="3 angles with scores and a final declaration of the winning angle.",
    agent=content_fit_scorer
)

task_content = Task(
    description="Using the winning angle, write a highly engaging, authoritative 500-word article or long-form LinkedIn post." + get_system_guardrail(TARGET_TOPICS),
    expected_output="A final, polished piece of content in Markdown format.",
    agent=content_writer
)

print('Initialized tasks successfully')

"""# The Crew"""

import asyncio

crew = Crew(
    agents=[expertise_analyst, topic_researcher, content_fit_scorer, content_writer],
    tasks=[task_expertise, task_research, task_score, task_content],
    verbose=False,
    max_rpm=15 # Keeps the free Gemini tier from crashing
)

async def execute_with_retry():
    # Clean async retry loop
    for attempt in range(1, 4):
        try:
            print(f'🚀 Starting Content Specialist crew (Attempt {attempt} of 3)...\n')

            result = await crew.kickoff_async()

            print("\n✅ Successfully executed the crew!")
            return result # Exit function successfully and return the data

        except Exception as e:
            # Catches BOTH 503 (High Demand) and 429 (Rate Limit) errors
            if "503" in str(e) or "429" in str(e):
                print(f"⚠️ Google API is busy. Waiting {attempt * 5} seconds...")
                await asyncio.sleep(attempt * 5)
            else:
                # If it's a real code error, stop immediately and show it
                raise e

    # This triggers ONLY if the loop finishes all 3 attempts without returning
    print("❌ Execution failed: Google's API is too busy right now. Try again later.")
    return None

result = await execute_with_retry()

if result:
    print("Successfully implemented the Crew")
    print(result.raw)